project:
  type: website
  output-dir: docs

website:
  navbar:
    background: primary
    search: true
    left:
    - text: "Workshop 3"
      menu:
        - workshop3/03workshop.qmd
        - workshop3/03A.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true


