project:
  type: website
  output-dir: docs

website:
  navbar:
    background: primary
    search: true
    left:
    - text: BM424 MyPlace
    - text: Workshop Overview/Instructions
      href: workshop3/03workshop.qmd
    - text: "Group Pages"
      menu:
        - workshop3/03A.qmd
    - text: "Data Analysis"
      menu: 
        - Data_Demographics.qmd
        - Data_Polling.qmd
        - Data_Budget.qmd
        - Data_Deaths.qmd
        - Data_Hospital.qmd
        - Data_16S.qmd
    tools:
      - icon: github
        href: https://github.com/mafeeney/BM424workshop3
      - icon: envelope
        href: mailto:morgan.feeney@strath.ac.uk
        
format:
  html:
    theme: simplex
    css: styles.css
    toc: false
    page-layout: full
    email-obfuscation: javascript

execute:
  freeze: auto


