project:
  type: website
  output-dir: docs

website:
  navbar:
    background: primary
    search: true
    left:
      - text: BM424 MyPlace
      - text: Workshop Overview/Instructions
        href: workshop3/03workshop.qmd
      - text: "Group Pages"
        menu:
          - text: "03A"
            href: workshop3/03A.qmd
      - text: "Data Analysis"
        menu: 
          - text: "Demographics"
            href: Data_Demographics.qmd
          - text: "Polling"
            href: Data_Polling.qmd
          - text: "Budget"
            href: Data_Budget.qmd
          - text: "Deaths"
            href: Data_Deaths.qmd
          - text: "Hospital"
            href: Data_Hospital.qmd
          - text: "16S"
            href: Data_16S.qmd
    tools:
      - icon: github
        href: https://github.com/mafeeney/BM424workshop3
      - icon: envelope
        href: mailto:morgan.feeney@strath.ac.uk
        
format:
  html:
    theme: simplex
    css: styles.css
    toc: false
    page-layout: full
    email-obfuscation: javascript

execute:
  freeze: auto


