---
title: "Workshop 3--Overview"
---

## BM424 Clinical Microbiology workshop 3 - Pandemic Response



### Overview of tasks:

*1. Prepare for the team meeting*

There are a number of data analysis/literature search tasks that each group will need to perform to prepare for the meeting. 

::: callout-tip
As a group, you should decide who will be responsible for which task(s) and how to allocate the work fairly. One possible way to divide the workload amongst your group is by choosing/allocating roles based on subject specialism, e.g.: 

# Roles and Responsibilities

## Epidemiologist/Public Health Tasks

- **Clinical Microbiologist role: diagnostic methods**
    - Analyse the sequence data collected from the outbreak thus far to confirm the etiology of the disease in each case.
    - Read the suggested references/search the literature (e.g., read the UK SMI document) to understand the diagnostic methods that could be useful for testing patients/residents for this particular pathogen.

- **Epidemiologist role: demographics**
    - Analyse your city's demographic data.
    - Read the suggested references/search the literature to understand what demographic groups will be at higher risk from this particular pathogen.

- **Epidemiologist role: pandemic effect analysis**
    - Analyse your city's death certificate data.
    - Read the suggested references/search the literature to understand the scope of the pandemic's effect on your city and what measures can be taken to stop the pathogen's transmission/reduce the severity of illness.

- **Hospital Director role: hospital case data**
    - Analyse your hospital's case data and dashboard.
    - Read the suggested references/search the literature to understand the scope of the pandemic's effect on your hospital and what measures can be taken to stop the pathogen's transmission/what resources are available.

- **Doctor/GP role**
    - Responsibilities to be defined.

## Resource Management/Planning Tasks

- **City Planner/Civil Servant role: resource determination**
    - Analyse your city's budget data to determine what resources your city has available to deal with this crisis.
    - Read the suggested references/search the literature to determine what measures have been shown to be effective (and cost-effective) for containing the spread of this particular pathogen, or pathogens transmitted via similar routes.

- **Public Communications Expert role**
    - Analyse opinion data to inform your public communications/outreach strategies.
    - Read the suggested references/search the literature to determine what measures have been shown to be effective (and supported by the public) for containing the spread of this particular pathogen, or pathogens transmitted via similar routes.
    
- **Provost/City Council member role**
    - Analyse polling data to inform your understanding of public support for the ciy council's policies
    - Read the suggested references/search the literature to determine what measures the council are legally 

:::


*2. Emergency Pandemic Response Team Meeting*

        
::: callout-tip
Your decisions should be evidence-based
:::


*3. submit committee decisions*

::: callout-important
:::


